# AppVeyor configuration based on https://github.com/guedou/scapy-appveyor/blob/master/appveyor.yml

environment:

  # Python versions that will be tested
  # Note: it defines variables that can be used later
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

# Install requirements
install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  # Installing WinPcap directly does not work,
  # see http://help.appveyor.com/discussions/problems/2280-winpcap-installation-issue
  - cinst nmap
  - refreshenv
  - pip install Sphinx==1.4.5

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py test"
  - "build.cmd %PYTHON%\\python.exe setup.py doc"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
