language: python

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: false
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 2.7
          sudo: false
          env:
            - CXX=g++ CC=gcc

        - os: osx
          language: generic
          sudo: required

    allow_failures:
        - os: osx

before_script:
  # Install system requirements for OSX (pylibpcap and libdnet)
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then sudo brew install --with-python libdnet; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then sudo brew install https://raw.githubusercontent.com/secdev/scapy/master/.travis/pylibpcap.rb; fi

install:
  - pip install .
  - pip install Sphinx==1.4.5

script:
  - python setup.py test
  - python setup.py doc
